# Generated by Django 3.2.25 on 2025-03-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
